FROM openjdk

COPY --chown=0:0 --chmod=775 ./zookeeper /zookeeper
COPY --chown=0:0 --chmod=775 ./zoo.cfg /zookeeper/conf
COPY --chown=0:0 --chmod=775 ./myid_3 /var/lib/zookeeper/myid

COPY --chown=0:0 --chmod=775 ./kafka /kafka
COPY --chown=0:0 --chmod=775 ./server3.properties /kafka/config/server.properties

WORKDIR /
ENTRYPOINT [ "/bin/bash" ]

EXPOSE 2181
EXPOSE 2888
EXPOSE 3888
EXPOSE 9092
