services:
  kafka01:
    build:
      dockerfile: Dockerfile-kafka1
      no_cache: true
    image: kafka-img-01
    volumes:
      - ./lib_zkp1:/var/lib/zookeeper
    ports:
      - "21811:2181"
      - "28881:2888"
      - "38881:3888"
      - "19092:9092"
    container_name: kafka-cont-01
    stdin_open: true
    tty: true
    networks:
      - network-kafka
    hostname: kafka1
# ----------------------------------------
  kafka02:
    build:
      dockerfile: Dockerfile-kafka2
      no_cache: true
    image: kafka-img-02
    volumes:
      - ./lib_zkp2:/var/lib/zookeeper
    ports:
      - "21812:2181"
      - "28882:2888"
      - "38882:3888"
      - "29092:9092"
    container_name: kafka-cont-02
    stdin_open: true
    tty: true
    networks:
      - network-kafka
    hostname: kafka2
# ----------------------------------------
  kafka03:
    build:
      dockerfile: Dockerfile-kafka3
      no_cache: true
    image: kafka-img-03
    volumes:
      - ./lib_zkp3:/var/lib/zookeeper
    ports:
      - "21813:2181"
      - "28883:2888"
      - "38883:3888"
      - "39092:9092"
    container_name: kafka-cont-03
    stdin_open: true
    tty: true
    networks:
      - network-kafka
    hostname: kafka3
# ----------------------------------------
  kafka-consumer:
    depends_on:
      - kafka01
      - kafka02
      - kafka03
    build:
      dockerfile: Dockerfile-consumer
      no_cache: true
    image: kafka-img-consumer
    container_name: kafka-cont-consumer
    stdin_open: true
    tty: true
    networks:
      - network-kafka
    hostname: kafka-consumer
# ----------------------------------------
  kafka-producer:
    depends_on:
      - kafka01
      - kafka02
      - kafka03
      - kafka-consumer
    build:
      dockerfile: Dockerfile-producer
      no_cache: true
    image: kafka-img-producer
    container_name: kafka-cont-producer
    stdin_open: true
    tty: true
    networks:
      - network-kafka
    hostname: kafka-producer
# ----------------------------------------
# ========================================
networks:
  network-kafka:
    driver: bridge
