FROM openjdk
COPY --chown=0:0 --chmod=775 ./kafka /kafka

WORKDIR /
ENTRYPOINT [ "/kafka/bin/kafka-console-consumer.sh", "--bootstrap-server", "kafka1:9092,kafka2:9092,kafka3:9092", "--topic", "mytest", "--from-beginning" ]
